spring.application.name=sortiz-ecom

#minimum config needs to get the db config up and running
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test-db

# config to log sqls - only for debug
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=create-drop

# project images path
project.images=images/
